name: Update Reading List
on: [workflow_dispatch, push]
  
  
jobs:
  update_reading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.10' 
    - run: |
        python reading/adsabs.py > tmp.txt
        sed -i '/<!-- READINGLIST:START -->/,/<!-- READINGLIST:END -->/d' README.md
        echo '<!-- READINGLIST:START -->' >> README.md
        cat tmp.txt >> README.md
        echo '<!-- READINGLIST:END -->' >> README.md
        cat README.md
