name: Update Reading List
on:
  workflow_dispatch:
  
jobs:
  update_reading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.10' 
    - name: Run the stuff
      env: 
        ADSABS_TOKEN: ${{ secrets.ADSABS_TOKEN }}
      run: |
        pip install ads
        python py/adsabs.py > tmp.txt
        sed -n -i '1,/<!-- READINGLIST:START -->/p;/<!-- READINGLIST:END -->/,$p' README.md
        sed -i -e '/<!-- READINGLIST:START -->/r tmp.txt' README.md
        sed -i -e '/<!-- READINGLIST:START -->/a \ ' README.md
    - name: stage changed files
      run: git add README.md
    - name: Commit files
      run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updating reading list" -a
          git pull
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
