name: Update Resume
on:
  push:
  
jobs:
  update_cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clone overleaf
        run: |
          git clone https://spencerriley620%40gmail.com:${{ secrets.overleaf }}@git.overleaf.com/5e87506aa3afa80001813f3d
          ls 5e87506aa3afa80001813f3d/
      - name: Compile
        uses: birjolaxew/tectonic-biber-action@master
        with:
          files: 5e87506aa3afa80001813f3d/resume.tex
      - name: Add and commit
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: Update Resume
          add: '5e87506aa3afa80001813f3d/resume.pdf'
